// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using System.Collections;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class DropDownBoxResult
    {

        [JsonProperty("result")]
        public IList<IList<string>> Result { get; set; }

        [JsonProperty("magic")]
        public IList<Magic> Magic { get; set; }

    }
    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Magic
    {

        [JsonProperty("index")]
        public string Index { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

       [JsonProperty("data")]
       public IList<IList<Disc>> Data { get; set; }
    }
    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Disc
    {
        public string Title { get; set; }
        public string Type { get; set; }
    }
}