// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class KeySearchResult
    {

        [JsonProperty("pageName")]
        public string PageName { get; set; }

        [JsonProperty("mods")]
        public Mods Mods { get; set; }

        [JsonProperty("mainInfo")]
        public MainInfo MainInfo { get; set; }

        [JsonProperty("feature")]
        public Feature Feature { get; set; }
    }

}
