// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Auction
    {

        [JsonProperty("i2iTags")]
        public I2iTags I2iTags { get; set; }

        [JsonProperty("p4pTags")]
        public IList<object> P4pTags { get; set; }

        [JsonProperty("nid")]
        public string Nid { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("pid")]
        public string Pid { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("raw_title")]
        public string RawTitle { get; set; }

        [JsonProperty("pic_url")]
        public string PicUrl { get; set; }

        [JsonProperty("detail_url")]
        public string DetailUrl { get; set; }

        [JsonProperty("view_price")]
        public string ViewPrice { get; set; }

        [JsonProperty("view_fee")]
        public string ViewFee { get; set; }

        [JsonProperty("item_loc")]
        public string ItemLoc { get; set; }

        [JsonProperty("view_sales")]
        public string ViewSales { get; set; }

        [JsonProperty("comment_count")]
        public string CommentCount { get; set; }

        [JsonProperty("user_id")]
        public string UserId { get; set; }

        [JsonProperty("nick")]
        public string Nick { get; set; }

        [JsonProperty("shopcard")]
        public Shopcard Shopcard { get; set; }

        [JsonProperty("icon")]
        public IList<Icon> Icon { get; set; }

        [JsonProperty("comment_url")]
        public string CommentUrl { get; set; }

        [JsonProperty("shopLink")]
        public string ShopLink { get; set; }

        [JsonProperty("risk")]
        public string Risk { get; set; }
    }

}
