// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Data9
    {

        [JsonProperty("baobeiExtraClass")]
        public string BaobeiExtraClass { get; set; }

        [JsonProperty("etaoAds")]
        public bool EtaoAds { get; set; }

        [JsonProperty("p4pconfig")]
        public P4pconfig P4pconfig { get; set; }

        [JsonProperty("p4pdata")]
        public string P4pdata { get; set; }
    }

}
