// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Data7
    {

        [JsonProperty("breadcrumbs")]
        public Breadcrumbs Breadcrumbs { get; set; }

        [JsonProperty("hidenav")]
        public bool Hidenav { get; set; }
    }

}
