// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Data10
    {

        [JsonProperty("q")]
        public string Q { get; set; }

        [JsonProperty("tabParams")]
        public TabParams TabParams { get; set; }

        [JsonProperty("dropdown")]
        public IList<Dropdown> Dropdown { get; set; }

        [JsonProperty("imgBtn")]
        public bool ImgBtn { get; set; }

        [JsonProperty("uploadUrl")]
        public string UploadUrl { get; set; }

        [JsonProperty("hb")]
        public bool Hb { get; set; }

        [JsonProperty("hb_v")]
        public string HbV { get; set; }
    }

}
