// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Data3
    {

        [JsonProperty("render")]
        public bool Render { get; set; }

        [JsonProperty("useOld")]
        public bool UseOld { get; set; }

        [JsonProperty("showType")]
        public string ShowType { get; set; }

        [JsonProperty("pingce")]
        public string Pingce { get; set; }
    }

}
