// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class DropdownList
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("tip")]
        public string Tip { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("trace")]
        public string Trace { get; set; }
    }

}
