// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Feature
    {

        [JsonProperty("webpOff")]
        public bool WebpOff { get; set; }

        [JsonProperty("retinaOff")]
        public bool RetinaOff { get; set; }

        [JsonProperty("shopcardOff")]
        public bool ShopcardOff { get; set; }
    }

}
