// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Icon
    {

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("dom_class")]
        public string DomClass { get; set; }

        [JsonProperty("position")]
        public string Position { get; set; }

        [JsonProperty("show_type")]
        public string ShowType { get; set; }

        [JsonProperty("icon_category")]
        public string IconCategory { get; set; }

        [JsonProperty("outer_text")]
        public string OuterText { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("icon_key")]
        public string IconKey { get; set; }

        [JsonProperty("trace")]
        public string Trace { get; set; }

        [JsonProperty("traceIdx")]
        public int TraceIdx { get; set; }

        [JsonProperty("innerText")]
        public string InnerText { get; set; }

        [JsonProperty("iconPopupComplex")]
        public IconPopupComplex IconPopupComplex { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("iconPopupNormal")]
        public IconPopupNormal IconPopupNormal { get; set; }
    }

}
