// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class IconPopupComplex
    {

        [JsonProperty("popup_title")]
        public string PopupTitle { get; set; }

        [JsonProperty("subIcons")]
        public IList<SubIcon> SubIcons { get; set; }
    }

}
