// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Location
    {

        [JsonProperty("active")]
        public string Active { get; set; }

        [JsonProperty("guessLoc")]
        public string GuessLoc { get; set; }

        [JsonProperty("usualLoc")]
        public IList<object> UsualLoc { get; set; }
    }

}
