// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class ModLinks
    {

        [JsonProperty("filter")]
        public string Filter { get; set; }

        [JsonProperty("default")]
        public string Default { get; set; }

        [JsonProperty("nav")]
        public string Nav { get; set; }

        [JsonProperty("breadcrumb")]
        public string Breadcrumb { get; set; }

        [JsonProperty("pager")]
        public string Pager { get; set; }

        [JsonProperty("tab")]
        public string Tab { get; set; }

        [JsonProperty("sortbar")]
        public string Sortbar { get; set; }
    }

}
