// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Mods
    {

        [JsonProperty("shopcombotip")]
        public Shopcombotip Shopcombotip { get; set; }

        [JsonProperty("phonenav")]
        public Phonenav Phonenav { get; set; }

        [JsonProperty("debugbar")]
        public Debugbar Debugbar { get; set; }

        [JsonProperty("shopcombo")]
        public Shopcombo Shopcombo { get; set; }

        [JsonProperty("itemlist")]
        public Itemlist Itemlist { get; set; }

        [JsonProperty("bottomsearch")]
        public Bottomsearch Bottomsearch { get; set; }

        [JsonProperty("tips")]
        public Tips Tips { get; set; }

        [JsonProperty("feedback")]
        public Feedback Feedback { get; set; }

        [JsonProperty("navtabtags")]
        public Navtabtags Navtabtags { get; set; }

        [JsonProperty("sc")]
        public Sc Sc { get; set; }

        [JsonProperty("bgshopstar")]
        public Bgshopstar Bgshopstar { get; set; }

        [JsonProperty("spuseries")]
        public Spuseries Spuseries { get; set; }

        [JsonProperty("related")]
        public Related Related { get; set; }

        [JsonProperty("tab")]
        public Tab Tab { get; set; }

        [JsonProperty("pager")]
        public Pager Pager { get; set; }

        [JsonProperty("apasstips")]
        public Apasstips Apasstips { get; set; }

        [JsonProperty("tbcode")]
        public Tbcode Tbcode { get; set; }

        [JsonProperty("vbaby")]
        public Vbaby Vbaby { get; set; }

        [JsonProperty("hongbao")]
        public Hongbao Hongbao { get; set; }

        [JsonProperty("nav")]
        public Nav Nav { get; set; }

        [JsonProperty("sortbar")]
        public Sortbar Sortbar { get; set; }

        [JsonProperty("d11filterbar")]
        public D11filterbar D11filterbar { get; set; }

        [JsonProperty("personalbar")]
        public Personalbar Personalbar { get; set; }

        [JsonProperty("p4p")]
        public P4p P4p { get; set; }

        [JsonProperty("choosecar")]
        public Choosecar Choosecar { get; set; }

        [JsonProperty("shopstar")]
        public Shopstar Shopstar { get; set; }

        [JsonProperty("header")]
        public Header Header { get; set; }

        [JsonProperty("spucombo")]
        public Spucombo Spucombo { get; set; }

        [JsonProperty("supertab")]
        public Supertab Supertab { get; set; }

        [JsonProperty("navtablink")]
        public Navtablink Navtablink { get; set; }

        [JsonProperty("noresult")]
        public Noresult Noresult { get; set; }
    }

}
