// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class P4pconfig
    {

        [JsonProperty("keyword")]
        public string Keyword { get; set; }

        [JsonProperty("keywordGBK")]
        public string KeywordGBK { get; set; }

        [JsonProperty("catid")]
        public string Catid { get; set; }

        [JsonProperty("propertyid")]
        public string Propertyid { get; set; }

        [JsonProperty("ip")]
        public string Ip { get; set; }

        [JsonProperty("loc")]
        public string Loc { get; set; }

        [JsonProperty("gprice")]
        public string Gprice { get; set; }

        [JsonProperty("sort")]
        public string Sort { get; set; }

        [JsonProperty("sbid")]
        public string Sbid { get; set; }

        [JsonProperty("q2cused")]
        public int Q2cused { get; set; }

        [JsonProperty("pageNum")]
        public int PageNum { get; set; }

        [JsonProperty("p4pbottom_up")]
        public bool P4pbottomUp { get; set; }

        [JsonProperty("b2b_show")]
        public bool B2bShow { get; set; }

        [JsonProperty("etao_wanke")]
        public bool EtaoWanke { get; set; }

        [JsonProperty("etao_effect")]
        public bool EtaoEffect { get; set; }

        [JsonProperty("offset")]
        public int Offset { get; set; }

        [JsonProperty("refpid")]
        public string Refpid { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("xmatch")]
        public int Xmatch { get; set; }

        [JsonProperty("rn")]
        public string Rn { get; set; }

        [JsonProperty("ismall")]
        public string Ismall { get; set; }

        [JsonProperty("srp")]
        public string Srp { get; set; }

        [JsonProperty("tags")]
        public string Tags { get; set; }

        [JsonProperty("p4p_btsinfo")]
        public string P4pBtsinfo { get; set; }

        [JsonProperty("auction_tag")]
        public string AuctionTag { get; set; }

        [JsonProperty("has_sku_pic")]
        public bool HasSkuPic { get; set; }

        [JsonProperty("firstpage_auction_num")]
        public string FirstpageAuctionNum { get; set; }

        [JsonProperty("auction_num")]
        public AuctionNum AuctionNum { get; set; }

        [JsonProperty("time")]
        public string Time { get; set; }

        [JsonProperty("tianmu_type")]
        public string TianmuType { get; set; }

        [JsonProperty("refinfo")]
        public string Refinfo { get; set; }
    }

}
