// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class Shopcard
    {

        [JsonProperty("levelClasses")]
        public IList<_LevelClass> LevelClasses { get; set; }

        [JsonProperty("isTmall")]
        public bool IsTmall { get; set; }

        [JsonProperty("delivery")]
        public IList<int> Delivery { get; set; }

        [JsonProperty("description")]
        public IList<int> Description { get; set; }

        [JsonProperty("service")]
        public IList<int> Service { get; set; }

        [JsonProperty("encryptedUserId")]
        public string EncryptedUserId { get; set; }

        [JsonProperty("sellerCredit")]
        public int SellerCredit { get; set; }

        [JsonProperty("totalRate")]
        public int TotalRate { get; set; }
    }

}
