// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class SrpGlobal
    {

        [JsonProperty("q")]
        public string Q { get; set; }

        [JsonProperty("encode_q")]
        public string EncodeQ { get; set; }

        [JsonProperty("utf8_q")]
        public string Utf8Q { get; set; }

        [JsonProperty("cat")]
        public string Cat { get; set; }

        [JsonProperty("catLevelOne")]
        public string CatLevelOne { get; set; }

        [JsonProperty("s")]
        public int S { get; set; }

        [JsonProperty("bucketid")]
        public int Bucketid { get; set; }

        [JsonProperty("multi_bucket")]
        public string MultiBucket { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("machine")]
        public string Machine { get; set; }

        [JsonProperty("buckets")]
        public string Buckets { get; set; }

        [JsonProperty("sp_url")]
        public string SpUrl { get; set; }

        [JsonProperty("srpName")]
        public string SrpName { get; set; }
    }

}
