// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class SubIcon
    {

        [JsonProperty("dom_class")]
        public string DomClass { get; set; }

        [JsonProperty("icon_content")]
        public string IconContent { get; set; }
    }

}
