// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class TabParams
    {

        [JsonProperty("js")]
        public string Js { get; set; }

        [JsonProperty("stats_click")]
        public string StatsClick { get; set; }

        [JsonProperty("initiative_id")]
        public string InitiativeId { get; set; }

        [JsonProperty("ie")]
        public string Ie { get; set; }
    }

}
