// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CQ.Entity;

namespace CQ.Entity
{

    [Obfuscation(Feature = "trigger", Exclude = false)]
    public class TraceData2
    {

        [JsonProperty("catdirect")]
        public string Catdirect { get; set; }

        [JsonProperty("remoteip")]
        public string Remoteip { get; set; }

        [JsonProperty("tabType")]
        public string TabType { get; set; }

        [JsonProperty("is_rs")]
        public string IsRs { get; set; }

        [JsonProperty("catpredict_bury")]
        public string CatpredictBury { get; set; }

        [JsonProperty("hostname")]
        public string Hostname { get; set; }

        [JsonProperty("activityClick")]
        public IList<string> ActivityClick { get; set; }

        [JsonProperty("lastAlitrackid")]
        public string LastAlitrackid { get; set; }

        [JsonProperty("at_lflog")]
        public string AtLflog { get; set; }

        [JsonProperty("list_model")]
        public string ListModel { get; set; }

        [JsonProperty("page_size")]
        public string PageSize { get; set; }

        [JsonProperty("rsPositions")]
        public IList<string> RsPositions { get; set; }

        [JsonProperty("if_tank")]
        public string IfTank { get; set; }

        [JsonProperty("rsshop")]
        public string Rsshop { get; set; }

        [JsonProperty("alitrackid")]
        public string Alitrackid { get; set; }

        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonProperty("price_rank")]
        public string PriceRank { get; set; }

        [JsonProperty("sort")]
        public string Sort { get; set; }

        [JsonProperty("catLevelOne")]
        public string CatLevelOne { get; set; }

        [JsonProperty("auctionNids")]
        public IList<string> AuctionNids { get; set; }

        [JsonProperty("ifDoufuAuction")]
        public IList<string> IfDoufuAuction { get; set; }

        [JsonProperty("at_host")]
        public string AtHost { get; set; }

        [JsonProperty("querytype_bury")]
        public string QuerytypeBury { get; set; }

        [JsonProperty("allOldBiz30Day")]
        public IList<string> AllOldBiz30Day { get; set; }

        [JsonProperty("tdTags")]
        public string TdTags { get; set; }

        [JsonProperty("relateHotTrace")]
        public IList<string> RelateHotTrace { get; set; }

        [JsonProperty("totalHits")]
        public string TotalHits { get; set; }

        [JsonProperty("allCategories")]
        public IList<string> AllCategories { get; set; }

        [JsonProperty("auctionIconServices")]
        public IList<string> AuctionIconServices { get; set; }

        [JsonProperty("rn")]
        public string Rn { get; set; }

        [JsonProperty("isp4p")]
        public IList<string> Isp4p { get; set; }

        [JsonProperty("rs")]
        public string Rs { get; set; }

        [JsonProperty("colo")]
        public string Colo { get; set; }

        [JsonProperty("allPrices")]
        public IList<string> AllPrices { get; set; }

        [JsonProperty("show_compass")]
        public string ShowCompass { get; set; }

        [JsonProperty("auctionPrices")]
        public IList<string> AuctionPrices { get; set; }

        [JsonProperty("auctionReturnNum")]
        public string AuctionReturnNum { get; set; }

        [JsonProperty("multivariate")]
        public string Multivariate { get; set; }

        [JsonProperty("p4pDelTraceInfo")]
        public IList<object> P4pDelTraceInfo { get; set; }

        [JsonProperty("bucketId")]
        public string BucketId { get; set; }

        [JsonProperty("rewrite_bury")]
        public string RewriteBury { get; set; }

        [JsonProperty("allPersonalUpReason")]
        public IList<string> AllPersonalUpReason { get; set; }

        [JsonProperty("allDoufuNids")]
        public IList<object> AllDoufuNids { get; set; }

        [JsonProperty("priceSorts")]
        public IList<string> PriceSorts { get; set; }

        [JsonProperty("at_bucketid")]
        public string AtBucketid { get; set; }

        [JsonProperty("srppage")]
        public string Srppage { get; set; }

        [JsonProperty("if_rs")]
        public string IfRs { get; set; }

        [JsonProperty("allNids")]
        public IList<string> AllNids { get; set; }

        [JsonProperty("cat")]
        public string Cat { get; set; }

        [JsonProperty("spUrl")]
        public string SpUrl { get; set; }

        [JsonProperty("sort2")]
        public string Sort2 { get; set; }

        [JsonProperty("qp_bury")]
        public string QpBury { get; set; }

        [JsonProperty("doufuAuctionNum")]
        public string DoufuAuctionNum { get; set; }

        [JsonProperty("at_colo")]
        public string AtColo { get; set; }

        [JsonProperty("bandit")]
        public string Bandit { get; set; }

        [JsonProperty("rs_count")]
        public string RsCount { get; set; }

        [JsonProperty("has_sku_pic")]
        public string HasSkuPic { get; set; }

        [JsonProperty("from_pos")]
        public string FromPos { get; set; }

        [JsonProperty("statsClick")]
        public string StatsClick { get; set; }

        [JsonProperty("allDoufuPrices")]
        public IList<object> AllDoufuPrices { get; set; }

        [JsonProperty("rsKeywords")]
        public IList<string> RsKeywords { get; set; }

        [JsonProperty("tagList")]
        public IList<string> TagList { get; set; }

        [JsonProperty("auctionNicks")]
        public IList<string> AuctionNicks { get; set; }

        [JsonProperty("sp_seller_types")]
        public IList<string> SpSellerTypes { get; set; }

        [JsonProperty("catdirectForMaidian")]
        public string CatdirectForMaidian { get; set; }

        [JsonProperty("qinfo")]
        public string Qinfo { get; set; }

        [JsonProperty("noResultCode")]
        public string NoResultCode { get; set; }

        [JsonProperty("apass")]
        public string Apass { get; set; }

        [JsonProperty("spu_combo")]
        public string SpuCombo { get; set; }

        [JsonProperty("allTags")]
        public IList<string> AllTags { get; set; }

        [JsonProperty("multi_bucket")]
        public string MultiBucket { get; set; }

        [JsonProperty("navStatus")]
        public string NavStatus { get; set; }
    }

}
